../src/Reg_File/proof.v
../src/Reg_File/FF.v
../src/Reg_File/FFzero.v
../src/Reg_File/mux.v
../src/Reg_File/regFile.v
../src/Reg_File/decoder.v
../src/Control_Unit/Main_Controller.v
../src/Control_Unit/CoreMips.v
../src/Control_Unit/Control_Unit_TB.sv
../src/Control_Unit/ALU_Decoder.v
../src/Control_Unit/Control_Unit.v
../src/Data_Path/mux4to1.v
../src/Data_Path/Buffer.v
../src/Data_Path/SignExtend.v
../src/Data_Path/ALU.v
../src/Data_Path/mux2to1.v
../src/Data_Path/Buffer2Bus.v
../src/Data_Path/PC.v
../src/Data_Path/SignExtend8to16.v
../src/Data_Path/Data_Path.v
../src/Sistema_Mem/addrDecoder.v
../src/Sistema_Mem/addrDecoderROM.v
../src/Sistema_Mem/Program_Memory.v
../src/Sistema_Mem/Memory_System.v
../src/Sistema_Mem/memDec.v
../src/Sistema_Mem/addrDecoderRAM1.v
../src/Sistema_Mem/muxMEM.v
../src/Sistema_Mem/singlePortRAM.v
../src/GPIO/Frequency_Divisor.v
../src/GPIO/MIPS_Multicycle.v
../src/GPIO/Clock_Gen.v
../src/GPIO/cont_1s_RCO.v
